# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d822833233ab17491e182ea4757d2e29669debadfc370fe50204c480705e3b9e690740c2e92e301170ae63309b01cb5eaa678033c23f4675c7e07e570d716431

test:
  secret_key_base: 624d0ee296cad88516877ada83fe4998264e492d1f1dc78d16247b26790ac03ae83d4064fe409c0ddf99d12ce230f6c6f800cb4e6724b362038332751de7defa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
